services:
  bot:
    build: .
    ports:
      - 5000:5000
    environment:
      - SIMPLETIMER_TOKEN=${SIMPLETIMER_TOKEN}
      - SIMPLETIMER_SHARDS_COUNT=${SIMPLETIMER_SHARDS_COUNT}
      - SIMPLETIMER_DB_ADDRESS=db:5432
      - SIMPLETIMER_DB_SCHEME=${DB_SCHEME}
      - SIMPLETIMER_DB_USER=${DB_USER}
      - SIMPLETIMER_DB_PASS=${DB_PASS}
    volumes:
      - bot-storage:/app/var
    depends_on:
      - db
  db:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_SCHEME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db-storage:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  bot-storage:
  db-storage: